let grocery_items_list = [
    "Apples",
    "Bananas",
    "Milk",
    "Bread",
    "Eggs",
    "Chicken",
    "Rice",
    "Pasta",
    "Tomatoes",
    "Potatoes",
    "Onions",
    "Carrots",
    "Spinach",
    "Broccoli",
    "Cheese",
    "Yogurt",
    "Cereal",
    "Coffee",
    "Tea",
    "Orange Juice",
    "Cucumber",
    "Bell Peppers",
    "Strawberries",
    "Blueberries",
    "Salmon",
    "Ground Beef",
    "Olive Oil",
    "Salt",
    "Pepper",
    "Garlic",
    "Sugar",
    "Flour",
    "Baking Soda",
    "Honey",
    "Peanut Butter",
    "Jelly",
    "Soy Sauce",
    "Almond Milk",
    "Avocado",
    "Lettuce",
    "Green Beans",
    "Canned Beans",
    "Pineapple",
    "Grapes",
    "Kiwi",
    "Avocado",
    "Ground Turkey",
    "Oats",
    "Quinoa",
    "Lemon",
    "Lime",
    "Parmesan Cheese",
    "Basil",
    "Oregano",
    "Thyme",
    "Rosemary",
    "Vanilla Extract",
    "Cinnamon",
    "Nutmeg",
    "Cheddar Cheese",
    "Sour Cream",
    "Ice Cream",
    "Frozen Peas",
    "Frozen Corn",
    "Frozen Mixed Vegetables",
    "Frozen Berries",
    "Detergent",
    "Toilet Paper",
    "Paper Towels",
    "Trash Bags",
    "Dish Soap",
    "Hand Soap",
    "Shampoo",
    "Conditioner",
    "Toothpaste",
    "Toothbrush",
    "Floss",
    "Cat Food",
    "Dog Food",
    "Diapers",
    "Baby Wipes",
    "Tissues",
    "Aluminum Foil",
    "Plastic Wrap",
    "Ziploc Bags",
    "Batteries",
    "Light Bulbs",
    "Candles",
    "Matches",
    "Dishwasher Detergent",
    "Multi-Surface Cleaner",
    "Garbage Bags",
    "Oven Cleaner",
    "Glass Cleaner",
    "Hand Sanitizer",
    "Face Masks",
    "Disinfectant Wipes",
    "Sunscreen",
    "Bug Spray",
    "First Aid Kit",
    "Bandages",
    "Pain Relievers",
    "Cold Medicine",
    "Allergy Medicine",
    "Laundry Detergent",
    "Fabric Softener",
    "Dryer Sheets",
    "Bleach",
    "Vinegar",
    "Sponges",
    "Dish Scrubber",
    "Trash Can",
    "Broom",
    "Mop",
    "Bucket",
    "Vacuum Cleaner",
    "Storage Containers",
    "Zipper Bags",
    "Parchment Paper",
    "Plastic Cutlery",
    "Paper Plates",
    "Napkins",
    "Condiments",
    "Ketchup",
    "Mustard",
    "Mayonnaise",
    "Salsa",
    "Hot Sauce",
    "Pickles",
    "Salad Dressing",
    "BBQ Sauce",
    "Soy Milk",
    "Coconut Milk",
    "Ramen Noodles",
    "Peanuts",
    "Cashews",
    "Walnuts",
    "Trail Mix",
    "Granola",
    "Hummus",
    "Pita Bread",
    "Tortillas",
    "Sourdough Bread",
    "Bagels",
    "Cream Cheese",
    "Deli Meat",
    "Sausages",
    "Ham",
    "Turkey",
    "Salami",
    "Provolone Cheese",
    "Swiss Cheese",
    "Gouda Cheese",
    "Cottage Cheese",
    "Frozen Pizza",
    "Canned Soup",
    "Instant Ramen",
    "Macaroni and Cheese",
    "Peanut Oil",
    "Sesame Oil",
    "Worcestershire Sauce",
    "Balsamic Vinegar",
    "Red Wine Vinegar",
    "White Wine Vinegar",
    "Coconut Oil",
    "Brown Rice",
    "Quinoa",
    "Lentils",
    "Chickpeas",
    "Black Beans",
    "Kidney Beans",
    "Pinto Beans",
    "Barley",
    "Couscous",
    "Salsa",
    "Guacamole",
    "Taco Shells",
    "Taco Seasoning",
    "Chili Powder",
    "Cumin",
    "Paprika",
    "Cayenne Pepper",
    "Dried Basil",
    "Dried Oregano",
    "Dried Thyme",
    "Dried Rosemary",
    "Dried Parsley",
    "Dried Sage",
    "Bay Leaves",
    "Ground Cinnamon",
    "Ground Nutmeg",
    "Ground Cloves",
    "Dried Chili Flakes",
    "Black Pepper",
    "Sea Salt",
    "Oregano",
    "Basil",
    "Parsley",
    "Rosemary",
    "Thyme",
    "Chives",
    "Mint",
    "Coriander",
    "Cilantro",
    "Dill",
    "Bay Leaves",
    "Tarragon",
    "Sage",
    "Marjoram",
    "Fennel",
    "Turmeric",
    "Cumin",
    "Curry Powder",
    "Paprika",
    "Cayenne Pepper",
    "Garlic Powder",
    "Onion Powder",
    "Chili Powder",
    "Mustard Powder",
    "Celery Salt",
    "Vanilla Extract",
    "Almond Extract",
    "Maple Syrup",
    "Agave Syrup",
    "Honey",
    "Molasses",
    "Brown Sugar",
    "Powdered Sugar",
    "Cornstarch",
    "Baking Powder",
    "Baking Soda",
    "Cocoa Powder",
    "Chocolate Chips",
    "Raisins",
    "Dried Cranberries",
    "Dried Apricots",
    "Dried Figs",
    "Dried Mango",
    "Sunflower Seeds",
    "Pumpkin Seeds",
    "Chia Seeds",
    "Flaxseeds",
    "Popcorn Kernels",
    "Dark Chocolate",
    "Milk Chocolate",
    "White Chocolate",
    "Graham Crackers",
    "Marshmallows",
    "Chocolate Syrup",
    "Whipped Cream",
    "Pie Crust",
    "Canned Pumpkin",
    "Evaporated Milk",
    "Sweetened Condensed Milk",
    "Pecans",
    "Walnuts",
    "Cashews",
    "Macadamia",
    "Apples",
    "Bananas",
    "Milk",
    "Bread",
    "Eggs",
    "Chicken",
    "Rice",
    "Pasta",
    "Tomatoes",
    "Potatoes",
    "Onions",
    "Carrots",
    "Lettuce",
    "Cheese",
    "Yogurt",
    "Orange Juice",
    "Coffee",
    "Tea",
    "Sugar",
    "Salt",
    "Pepper",
    "Olive Oil",
    "Chicken Broth",
    "Canned Beans",
    "Peanut Butter",
    "Jelly",
    "Bacon",
    "Sausages",
    "Cereal",
    "Frozen Pizza",
    "Ice Cream",
    "Chocolate",
    "Chips",
    "Soda",
    "Water",
    "Almonds",
    "Detergent",
    "Toilet Paper",
    "Shampoo",
    "Soap",
    "Toothpaste",
    "Paper Towels",
    "Dish Soap",
    "Garlic",
    "Ginger",
    "Honey",
    "Mustard",
    "Mayonnaise",
    "Ketchup",
    "BBQ Sauce",
    "Cucumber",
    "Bell Peppers",
    "Broccoli",
    "Cauliflower",
    "Avocado",
    "Soy Sauce",
    "Vinegar",
    "Wine",
    "Beer",
    "Cheddar Cheese",
    "Parmesan Cheese",
    "Pineapple",
    "Strawberries",
    "Blueberries",
    "Raspberries",
    "Blackberries",
    "Cottage Cheese",
    "Salmon",
    "Tuna",
    "Crackers",
    "Cookies",
    "Oatmeal",
    "Canned Soup",
    "Ground Beef",
    "Salami",
    "Ham",
    "Turkey",
    "Frozen Vegetables",
    "Granola Bars",
    "Waffles",
    "Pancake Mix",
    "Maple Syrup",
    "Hummus",
    "Quinoa",
    "Canned Tuna",
    "Cranberry Sauce",
    "Pumpkin Puree",
    "Cinnamon",
    "Nutmeg",
    "Vanilla Extract",
    "Cumin",
    "Paprika",
    "Chili Powder",
    "Cayenne Pepper",
    "Black Beans",
    "Sour Cream",
    "Green Beans",
    "Corn",
    "Hot Sauce",
    "Salsa",
    "Tortilla Chips",
    "Lemon",
    "Lime",
    "Peaches",
    "Plums",
    "Grapes",
    "Melon",
    "Cantaloupe",
    "Honeydew",
    "Mango",
    "Pears",
    "Pomegranate",
    "Kiwi",
    "Radishes",
    "Asparagus",
    "Zucchini",
    "Artichokes",
    "Eggplant",
    "Beets",
    "Spinach",
    "Kale",
    "Swiss Chard",
    "Arugula",
    "Celery",
    "Mushrooms",
    "Peas",
    "Iceberg Lettuce",
    "Red Cabbage",
    "Green Cabbage",
    "Romaine Lettuce",
    "Brussels Sprouts",
    "Bok Choy",
    "Parsley",
    "Cilantro",
    "Dill",
    "Thyme",
    "Rosemary",
    "Basil",
    "Mint",
    "Oregano",
    "Papaya",
    "Dragon Fruit",
    "Passion Fruit",
    "Guava",
    "Starfruit",
    "Persimmon",
    "Coconut",
    "Hazelnuts",
    "Cashews",
    "Walnuts",
    "Pecans",
    "Macadamia Nuts",
    "Pistachios",
    "Sunflower Seeds",
    "Pumpkin Seeds",
    "Chia Seeds",
    "Flaxseeds",
    "Quince",
    "Mulberries",
    "Cantaloupe",
    "Fig",
    "Watermelon",
    "Borage",
    "Rutabaga",
    "Chard",
    "Kohlrabi",
    "Leeks",
    "Turnips",
    "Fennel",
    "Collard Greens",
    "Endive",
    "Escarole",
    "Jicama",
    "Persimmon",
    "Starfruit",
    "Lychee",
    "Papaya",
    "Goji Berries",
    "Acai Berries",
    "Kiwano",
    "Cherimoya",
    "Breadfruit",
    "Soursop",
    "Mango",
    "Ginger Root",
    "Turmeric",
    "Arrowroot",
    "Daikon Radish",
    "Hijiki Seaweed",
    "Kelp",
    "Nori Seaweed",
    "Wakame Seaweed",
    "Spaghetti Squash",
    "Acorn Squash",
    "Butternut Squash",
    "Delicata Squash",
    "Kabocha Squash",
    "Banana Squash",
    "Zucchini",
    "Celeriac",
    "Rutabaga",
    "Parsnip",
    "Salsify",
    "Jerusalem Artichoke",
    "Celeriac",
    "Okra",
    "Elderberries",
    "Currants",
    "Gooseberries",
    "Boysenberries",
    "Rhubarb",
    "Mirabelle Plums",
    "Damson Plums",
    "Greengage Plums",
    "Santa Rosa Plums",
    "Yellow Plums",
    "Champagne Grapes",
    "Concord Grapes",
    "Cotton Candy Grapes",
    "Moon Drop Grapes",
    "Muscat Grapes",
    "Red Globe Grapes",
    "Autumn Royal Grapes",
    "Thompson Seedless Grapes",
    "Black Currants",
    "Red Currants",
    "White Currants",
    "Cranberries",
    "Mango",
    "Pineapple",
    "Coconut",
    "Pomegranate",
    "Dragon Fruit",
    "Cactus Pear",
    "Passion Fruit",
    "Kiwi",
    "Starfruit",
    "Plantains",
    "Jackfruit",
    "Lemongrass",
    "Turmeric",
    "Galangal",
    "Wasabi",
    "Tamari",
    "Umeboshi Plums",
    "Pickled Ginger",
    "Miso Paste",
    "Sesame Oil",
    "Rice Vinegar",
    "Mirin",
    "Sake",
    "Sushi Rice",
    "Nori Sheets",
    "Wasabi",
    "Edamame",
    "Bamboo Shoots",
    "Water Chestnuts",
    "Chow Mein Noodles",
    "Ramen",
]

let grocery_list = []
grocery_items_list.forEach((item)=>{
    if(!grocery_list.includes(item)){
        grocery_list.push(item)
    }
})

export default(grocery_list)