let itemName = document.getElementById('itemName')
let metrics = document.getElementById('metrics')
let quantity = document.getElementById('quantity')
let section = document.getElementsByTagName('section')[0]
let addItemBtn = document.getElementById('addItemBtn')
let deleteAllBtn = document.getElementById('deleteAllBtn')
let itemsArray = (localStorage.getItem('items'))? JSON.parse(localStorage.getItem('items')) : []
let grocerylist = document.getElementById('grocerylist')

let grocery_items = [
    "Apples",
    "Bananas",
    "Milk",
    "Bread",
    "Eggs",
    "Chicken",
    "Rice",
    "Pasta",
    "Tomatoes",
    "Potatoes",
    "Onions",
    "Carrots",
    "Spinach",
    "Broccoli",
    "Cheese",
    "Yogurt",
    "Cereal",
    "Coffee",
    "Tea",
    "Orange Juice",
    "Cucumber",
    "Bell Peppers",
    "Strawberries",
    "Blueberries",
    "Salmon",
    "Ground Beef",
    "Olive Oil",
    "Salt",
    "Pepper",
    "Garlic",
    "Sugar",
    "Flour",
    "Baking Soda",
    "Honey",
    "Peanut Butter",
    "Jelly",
    "Soy Sauce",
    "Almond Milk",
    "Avocado",
    "Lettuce",
    "Green Beans",
    "Canned Beans",
    "Pineapple",
    "Grapes",
    "Kiwi",
    "Avocado",
    "Ground Turkey",
    "Oats",
    "Quinoa",
    "Lemon",
    "Lime",
    "Parmesan Cheese",
    "Basil",
    "Oregano",
    "Thyme",
    "Rosemary",
    "Vanilla Extract",
    "Cinnamon",
    "Nutmeg",
    "Cheddar Cheese",
    "Sour Cream",
    "Ice Cream",
    "Frozen Peas",
    "Frozen Corn",
    "Frozen Mixed Vegetables",
    "Frozen Berries",
    "Detergent",
    "Toilet Paper",
    "Paper Towels",
    "Trash Bags",
    "Dish Soap",
    "Hand Soap",
    "Shampoo",
    "Conditioner",
    "Toothpaste",
    "Toothbrush",
    "Floss",
    "Cat Food",
    "Dog Food",
    "Diapers",
    "Baby Wipes",
    "Tissues",
    "Aluminum Foil",
    "Plastic Wrap",
    "Ziploc Bags",
    "Batteries",
    "Light Bulbs",
    "Candles",
    "Matches",
    "Dishwasher Detergent",
    "Multi-Surface Cleaner",
    "Garbage Bags",
    "Oven Cleaner",
    "Glass Cleaner",
    "Hand Sanitizer",
    "Face Masks",
    "Disinfectant Wipes",
    "Sunscreen",
    "Bug Spray",
    "First Aid Kit",
    "Bandages",
    "Pain Relievers",
    "Cold Medicine",
    "Allergy Medicine",
    "Laundry Detergent",
    "Fabric Softener",
    "Dryer Sheets",
    "Bleach",
    "Vinegar",
    "Sponges",
    "Dish Scrubber",
    "Trash Can",
    "Broom",
    "Mop",
    "Bucket",
    "Vacuum Cleaner",
    "Storage Containers",
    "Zipper Bags",
    "Parchment Paper",
    "Plastic Cutlery",
    "Paper Plates",
    "Napkins",
    "Condiments",
    "Ketchup",
    "Mustard",
    "Mayonnaise",
    "Salsa",
    "Hot Sauce",
    "Pickles",
    "Salad Dressing",
    "BBQ Sauce",
    "Soy Milk",
    "Coconut Milk",
    "Ramen Noodles",
    "Peanuts",
    "Cashews",
    "Walnuts",
    "Trail Mix",
    "Granola",
    "Hummus",
    "Pita Bread",
    "Tortillas",
    "Sourdough Bread",
    "Bagels",
    "Cream Cheese",
    "Deli Meat",
    "Sausages",
    "Ham",
    "Turkey",
    "Salami",
    "Provolone Cheese",
    "Swiss Cheese",
    "Gouda Cheese",
    "Cottage Cheese",
    "Frozen Pizza",
    "Canned Soup",
    "Instant Ramen",
    "Macaroni and Cheese",
    "Peanut Oil",
    "Sesame Oil",
    "Worcestershire Sauce",
    "Balsamic Vinegar",
    "Red Wine Vinegar",
    "White Wine Vinegar",
    "Coconut Oil",
    "Brown Rice",
    "Quinoa",
    "Lentils",
    "Chickpeas",
    "Black Beans",
    "Kidney Beans",
    "Pinto Beans",
    "Barley",
    "Couscous",
    "Salsa",
    "Guacamole",
    "Taco Shells",
    "Taco Seasoning",
    "Chili Powder",
    "Cumin",
    "Paprika",
    "Cayenne Pepper",
    "Dried Basil",
    "Dried Oregano",
    "Dried Thyme",
    "Dried Rosemary",
    "Dried Parsley",
    "Dried Sage",
    "Bay Leaves",
    "Ground Cinnamon",
    "Ground Nutmeg",
    "Ground Cloves",
    "Dried Chili Flakes",
    "Black Pepper",
    "Sea Salt",
    "Oregano",
    "Basil",
    "Parsley",
    "Rosemary",
    "Thyme",
    "Chives",
    "Mint",
    "Coriander",
    "Cilantro",
    "Dill",
    "Bay Leaves",
    "Tarragon",
    "Sage",
    "Marjoram",
    "Fennel",
    "Turmeric",
    "Cumin",
    "Curry Powder",
    "Paprika",
    "Cayenne Pepper",
    "Garlic Powder",
    "Onion Powder",
    "Chili Powder",
    "Mustard Powder",
    "Celery Salt",
    "Vanilla Extract",
    "Almond Extract",
    "Maple Syrup",
    "Agave Syrup",
    "Honey",
    "Molasses",
    "Brown Sugar",
    "Powdered Sugar",
    "Cornstarch",
    "Baking Powder",
    "Baking Soda",
    "Cocoa Powder",
    "Chocolate Chips",
    "Raisins",
    "Dried Cranberries",
    "Dried Apricots",
    "Dried Figs",
    "Dried Mango",
    "Sunflower Seeds",
    "Pumpkin Seeds",
    "Chia Seeds",
    "Flaxseeds",
    "Popcorn Kernels",
    "Dark Chocolate",
    "Milk Chocolate",
    "White Chocolate",
    "Graham Crackers",
    "Marshmallows",
    "Chocolate Syrup",
    "Whipped Cream",
    "Pie Crust",
    "Canned Pumpkin",
    "Evaporated Milk",
    "Sweetened Condensed Milk",
    "Pecans",
    "Walnuts",
    "Cashews",
    "Macadamia"
]

grocery_items.forEach((item) => {
    let option = document.createElement('option')
    option.innerHTML = item
    grocerylist.appendChild(option)
})

let addItem = ()=>{
    let itemCard = 
    `<div class='card'>
        <div class='item-detail'>
            ${itemName.value} ${quantity.value}${metrics.value}
        </div>
        <div class='status-box'>
        </div>
    </div>`
    let template = document.createElement('template');
    template.innerHTML = itemCard;
    section.appendChild(template.content)
}

addItemBtn.addEventListener('click',addItem)